---
- name: Install Hashicorp Consul and Vault
  hosts: all
  become: yes
  tasks:
  - name: Common tasks
    include: common.yml
  - name: Install Consul Server/Client
    include: consul.yml
  - name: Install Vault
    include: vault.yml
